common: board_f: Fix build error when CONFIG_TRACE is not defined
When CONFIG_TRACE is not defined, definition of trace_early_init is not
compiled and we get following error.

common/libcommon.o:(.data.init_sequence_f+0xc): undefined reference to `trace_early_init'

While at it, also define reserve_trace only if CONFIG_TRACE is defined.

CC: Simon Glass <sjg@chromium.org>
Signed-off-by: Tushar Behera <tushar.behera@linaro.org>